### ISSUE TITLE
Comments too dark

### ISSUE THREAD

**Issue by urielzen** [dunstontc/dark-plus-syntax#2]
The color of the comments are too dark in my opinion. Is there a chance that this could be reverted back to the same green color from the original theme?
Thanks a lot!
![image](https://user-images.githubusercontent.com/7947179/48369251-a9446d80-e67b-11e8-8382-2775e039f537.png)

**Comment by kherock** [comment]
I also agree. It also wouldn't hurt to make the curly braces/brackets/etc. a few shades lighter as well. In the meantime, you can reset comments back to green in your user settings with

```json
    "editor.tokenColorCustomizations": {
		"textMateRules": [
            {
                "scope": [
                    "comment",
                    "comment.line.double-slash.js",
                    "comment.block.html",
                    "comment.block.handlebars"
                ],
                "settings": {
                    "foreground": "#608b4e"
                }
            },
        ]
    },
```

**Comment by urielzen** [comment]
Thank you. I'll try that

**Comment by seanwash** [comment]
@urielzen This sent me on a journey this morning 😂

Turns out that code has a neat little tool for inspecting tokens. That should make it a lot easier to tweak things.

https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector

**Comment by urielzen** [comment]
@seanwash those are great tips. Thanks a lot!

**Comment by WindSoilder** [comment]
The comment is too dark for me too, but I would suggest that make the comment lighter by default (if most people thinks the comment is too dark).
