### ISSUE TITLE
0.0.151 Diff background remove issues

### ISSUE THREAD

**Issue by urielzen** [dunstontc/dark-plus-syntax#7]
0.0.151 removed the background color to Diff window.
I believe that without the background color it is harder to identify where the new changes are happening.

![image](https://user-images.githubusercontent.com/7947179/64815862-1f4f8480-d56c-11e9-8c3b-0ccede76d8e7.png)

Compare with original
![image](https://user-images.githubusercontent.com/7947179/64815805-08109700-d56c-11e9-8721-2e65ef9ba5ce.png)

Also the scrolling bar does not show where the changes are happening anymore.
now:
![image](https://user-images.githubusercontent.com/7947179/64816014-70f80f00-d56c-11e9-9d8f-8a0fc94bd889.png)

before:
![image](https://user-images.githubusercontent.com/7947179/64816047-83724880-d56c-11e9-869c-9a01460ab0e2.png)

**Comment by urielzen** [comment]
bump

**Comment by chrisgbaker** [comment]
Definitely still an issue. It's caused me to pick a different theme until this is fixed, as it makes the diff tool very cumbersome, especially the lack of the sidebar.

**Comment by chrisgbaker** [comment]
In reading the docs, i believe this is an easy fix:
![image](https://user-images.githubusercontent.com/17983534/66160963-42180a80-e5f9-11e9-82ec-1e64acaca79f.png)
I believe this theme is specifying both, which may be messing this up now. Not sure if this is a new change to how VSCode applies themes.

**Comment by urielzen** [comment]
@chrisgbaker fortunately there is an option in vscode to install a previous version so you dont have to switch themes.

![image](https://user-images.githubusercontent.com/7947179/66179324-13685700-e62e-11e9-9b9f-56b3744aba33.png)

**Comment by chrisgbaker** [comment]
@urielzen thanks! I wasn’t sure if that would work or if it was due to a change in vscode, but I’ll try that tomorrow

**Comment by tcd** [comment]
Hey @urielzen and all,

Sorry I didn't see this earlier. I'll look into this asap, thank you for bringing it to my attention.
Will post progress back to this issue.

Thanks,
Clay

**Comment by tcd** [comment]
@urielzen @chrisgbaker y'all take a look at the highlighting in 0.0.154 and let me know if there are still any issues.

**Comment by urielzen** [comment]
Thanks, it works great with the latest version!
